### ISSUE TITLE
Modifier le parametre de la periode de coupure des instruments

### ISSUE THREAD

**Issue by jihanesayadi** [eost/pyRepImp#4]
Rendre ce parametre configurable en fonction du type de sismo au debut du lancement du programme.

ex:
prop=[0,120,0.707,1,0] => prop=[0,"Periode de coupure",0.707,1,0]

**Comment by mbdb** [comment]
Encore mieux:
Implémenter une option 'type':
if type=='t120':
    prop=[0,120,0.707,1,0]

**Comment by mbdb** [comment]
Seule la période est contrôlable car utile: option --period dans l'éxécutable repimp_analyser
Les autres paramètres seront implémenté quand il y en aura besoin.
